<?php
require __DIR__ . '/../../config/database.php'; require __DIR__ . '/../../config/auth.php';
require_role(ROLE_BASIC);
$stmt = $pdo->prepare('SELECT o.*, ps.pos_name, ps.receipt_footer_message FROM pos_orders o LEFT JOIN pos_settings ps ON ps.id=1 WHERE o.id=?'); $stmt->execute([(int)($_GET['id'] ?? 0)]); $order = $stmt->fetch();
if (!$order) exit('Receipt not found.');
$lines = $pdo->prepare('SELECT l.*, p.name product FROM pos_order_lines l JOIN products p ON p.id=l.product_id WHERE l.order_id=?'); $lines->execute([$order['id']]);
$payments = $pdo->prepare('SELECT pl.*, pm.name method FROM pos_payment_lines pl JOIN payment_methods pm ON pm.id=pl.payment_method_id WHERE pl.order_id=?'); $payments->execute([$order['id']]);
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><title>Receipt <?= e($order['order_number']) ?></title><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><style>body{max-width:420px;margin:24px auto;font-size:14px}.receipt{border:1px solid #ddd;padding:18px}.print-hide{margin-bottom:12px}@media print{.print-hide{display:none}.receipt{border:0}}</style></head><body><div class="print-hide"><button class="btn btn-primary" onclick="print()">Print Receipt</button> <a class="btn btn-outline-secondary" href="orders.php">Orders</a></div><main class="receipt"><h1 class="h4 text-center"><?= e($order['pos_name'] ?? 'Inventory POS') ?></h1><p class="text-center mb-1">Order <?= e($order['order_number']) ?></p><p class="text-center"><?= e($order['order_date']) ?></p><table class="table table-sm"><tbody><?php foreach ($lines as $l): ?><tr><td><?= e($l['product']) ?> × <?= $l['quantity'] ?></td><td class="text-end"><?= number_format((float)$l['subtotal'],2) ?></td></tr><?php endforeach; ?></tbody></table><div class="d-flex justify-content-between"><span>Total</span><b><?= number_format((float)$order['total_amount'],2) ?></b></div><div class="d-flex justify-content-between"><span>Tax</span><b><?= number_format((float)$order['tax'],2) ?></b></div><div class="d-flex justify-content-between fs-5"><span>Grand Total</span><b><?= number_format((float)$order['grand_total'],2) ?></b></div><hr><h2 class="h6">Payments</h2><?php foreach ($payments as $p): ?><div class="d-flex justify-content-between"><span><?= e($p['method']) ?></span><span><?= number_format((float)$p['amount'],2) ?></span></div><?php endforeach; ?><p class="text-center mt-3"><?= e($order['receipt_footer_message'] ?? 'Thank you!') ?></p></main></body></html>

