<?php
require __DIR__ . '/../../config/database.php'; require __DIR__ . '/../../config/auth.php';
require_login(); $title = 'Reports';
$from = $_GET['from'] ?? date('Y-m-01'); $to = $_GET['to'] ?? date('Y-m-d'); $method = $_GET['payment_method_id'] ?? ''; $user = $_GET['user_id'] ?? '';
$where = 'WHERE DATE(o.order_date) BETWEEN ? AND ?'; $params = [$from, $to];
if ($user) { $where .= ' AND o.user_id=?'; $params[] = (int)$user; }
if ($method) { $where .= ' AND EXISTS (SELECT 1 FROM pos_payment_lines x WHERE x.order_id=o.id AND x.payment_method_id=?)'; $params[] = (int)$method; }
$stmt = $pdo->prepare("SELECT COUNT(*) orders_count, COALESCE(SUM(o.grand_total),0) revenue FROM pos_orders o $where"); $stmt->execute($params); $sales = $stmt->fetch();
$productStmt = $pdo->prepare("SELECT p.name product, SUM(l.quantity) qty, SUM(l.subtotal) revenue FROM pos_order_lines l JOIN products p ON p.id=l.product_id JOIN pos_orders o ON o.id=l.order_id $where GROUP BY p.id ORDER BY revenue DESC"); $productStmt->execute($params); $products = $productStmt->fetchAll();
$categoryStmt = $pdo->prepare("SELECT COALESCE(c.name,'Uncategorized') category, SUM(l.subtotal) revenue FROM pos_order_lines l JOIN products p ON p.id=l.product_id LEFT JOIN categories c ON c.id=p.category_id JOIN pos_orders o ON o.id=l.order_id $where GROUP BY c.id ORDER BY revenue DESC"); $categoryStmt->execute($params); $categories = $categoryStmt->fetchAll();
$stock = $pdo->query("SELECT p.name, COALESCE(SUM(s.quantity),0) stock, p.expiry_date FROM products p LEFT JOIN stock_entries s ON s.product_id=p.id GROUP BY p.id ORDER BY stock ASC")->fetchAll();
$users = $pdo->query('SELECT id,name FROM users ORDER BY name')->fetchAll(); $methods = $pdo->query('SELECT id,name FROM payment_methods ORDER BY name')->fetchAll();
require __DIR__ . '/../../templates/header.php';
?>
<form class="panel mb-3 row g-2"><div class="col-md-2"><input class="form-control" type="date" name="from" value="<?= e($from) ?>"></div><div class="col-md-2"><input class="form-control" type="date" name="to" value="<?= e($to) ?>"></div><div class="col-md-3"><select class="form-select" name="user_id"><option value="">All users</option><?php foreach ($users as $u): ?><option value="<?= $u['id'] ?>" <?= $user == $u['id'] ? 'selected' : '' ?>><?= e($u['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><select class="form-select" name="payment_method_id"><option value="">All payments</option><?php foreach ($methods as $m): ?><option value="<?= $m['id'] ?>" <?= $method == $m['id'] ? 'selected' : '' ?>><?= e($m['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filter</button></div></form>
<div class="row g-3 mb-3"><div class="col-md-4"><div class="metric"><span>Total Sales</span><b><?= number_format((float)$sales['revenue'],2) ?></b></div></div><div class="col-md-4"><div class="metric"><span>Total Orders</span><b><?= e((string)$sales['orders_count']) ?></b></div></div><div class="col-md-4"><div class="metric"><span>Revenue</span><b><?= number_format((float)$sales['revenue'],2) ?></b></div></div></div>
<div class="row g-3"><div class="col-lg-6"><div class="panel"><h2 class="h5">Product Sales</h2><table class="table"><tbody><?php foreach ($products as $p): ?><tr><td><?= e($p['product']) ?></td><td><?= e((string)$p['qty']) ?></td><td class="text-end"><?= number_format((float)$p['revenue'],2) ?></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-lg-6"><div class="panel"><h2 class="h5">Category Sales</h2><table class="table"><tbody><?php foreach ($categories as $c): ?><tr><td><?= e($c['category']) ?></td><td class="text-end"><?= number_format((float)$c['revenue'],2) ?></td></tr><?php endforeach; ?></tbody></table></div></div><div class="col-12"><div class="panel"><h2 class="h5">Stock Reports</h2><table class="table"><thead><tr><th>Product</th><th>Current Stock</th><th>Expiry</th><th>Status</th></tr></thead><tbody><?php foreach ($stock as $s): $expired=$s['expiry_date'] && $s['expiry_date'] < date('Y-m-d'); $soon=$s['expiry_date'] && $s['expiry_date'] <= date('Y-m-d', strtotime('+30 days')); ?><tr><td><?= e($s['name']) ?></td><td><?= e((string)$s['stock']) ?></td><td><?= e($s['expiry_date']) ?></td><td><?= ((int)$s['stock'] <= 5 ? 'Low stock ' : '') . ($expired ? 'Expired' : ($soon ? 'Expiring soon' : 'OK')) ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
<?php require __DIR__ . '/../../templates/footer.php'; ?>

